/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if 1
#include <stdint.h>
#include "RCCH743ZI.h"
#include "GPIOH743ZI.h"
#include "h7pwr.h"
#include "stdbool.h"
#include "h7timer.h"
#include "h7nvic.h"
#include "main.h"
//#include "mpu_wrappers.h"


/* Define TIM3 base address */
/* Define TIM2 base address */
#define TIM2 ((TIM_TypeDef *)TIM2_BASE)

/* =====================================================================
 *  Timer interrupt flags in SR and DIER
 * ===================================================================== */
#define TIM_SR_CC2IF            (1U << 2)

//------------------- MPU specific ------------------------//
/**
 * @brief Size of the shared memory region.
 */
#define SHARED_MEMORY_SIZE 32
static uint8_t ucSharedMemory1[ SHARED_MEMORY_SIZE ] MPU_ALIGNMENT;
static uint8_t ucSharedMemory2[ SHARED_MEMORY_SIZE ] MPU_ALIGNMENT;
static uint8_t ucSharedMemory3[ SHARED_MEMORY_SIZE ] MPU_ALIGNMENT;
static uint8_t ucSharedMemory4[ SHARED_MEMORY_SIZE ] MPU_ALIGNMENT;
static uint8_t ucSharedMemory5[ SHARED_MEMORY_SIZE ] MPU_ALIGNMENT;
static uint8_t ucSharedMemory6[ SHARED_MEMORY_SIZE ] MPU_ALIGNMENT;
static volatile uint8_t ucROTaskFaultTracker[SHARED_MEMORY_SIZE] MPU_ALIGNMENT = { 0 };
//--------------------------------------------------------//

/* Board mapping used by all examples:
 *   LED    -> PB14
 *   Switch -> PG0   (assumed active-low; pressed = pin reads LOW)
 */
#define LED1_PORT        GPIOB
#define LED1_PIN         14
#define LED2_PORT        GPIOE
#define LED2_PIN         1

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#endif

//--------------- FreeRTOS specific ---------------//

void SystemClock_16MHz_HSI(void);
void SystemClock_400MHz_HSI(void);
void LED_Init(void);
void rcc_Clk_Enable(void);
bool power_config(void);
void timer_init(void);
void TIM2_handler(void);
void Led1_Task(void *val);
void Led2_Task(void *val);

//------------------- MPU specific ------------------------//

static StackType_t led1Stack[configMINIMAL_STACK_SIZE] __attribute__( ( aligned( configMINIMAL_STACK_SIZE * sizeof( StackType_t ) ) ) );
TaskHandle_t led1TaskHandle;
TaskParameters_t Led1_TaskPara =
{
	.pvTaskCode		= Led1_Task,
	.pcName			= "RegTest1",
	.usStackDepth	= configMINIMAL_STACK_SIZE,
	.pvParameters	= NULL,
	.uxPriority		= tskIDLE_PRIORITY,
	.puxStackBuffer	= led1Stack,
	.xRegions		=	{
							{ ucSharedMemory1,					SHARED_MEMORY_SIZE,	portMPU_REGION_READ_WRITE | portMPU_REGION_EXECUTE_NEVER	},
							{ ucSharedMemory2,					SHARED_MEMORY_SIZE,	portMPU_REGION_PRIVILEGED_READ_WRITE_UNPRIV_READ_ONLY | portMPU_REGION_EXECUTE_NEVER	},
							{ ( void * ) ucROTaskFaultTracker,	SHARED_MEMORY_SIZE,	portMPU_REGION_READ_WRITE | portMPU_REGION_EXECUTE_NEVER								},
							{ 0,								0,					0																						},
							//							//{ (void*)0x58020400, 				0x400, 				tskMPU_REGION_READ_ONLY | tskMPU_REGION_EXECUTE_NEVER | tskMPU_REGION_DEVICE_MEMORY},
						}
};


static StackType_t led2Stack[configMINIMAL_STACK_SIZE] MPU_ALIGNMENT;
TaskHandle_t led2TaskHandle;
TaskParameters_t Led2_TaskPara = 
{
    .pvTaskCode      = Led2_Task,
    .pcName          = "RegTest2",
    .usStackDepth    = configMINIMAL_STACK_SIZE,
    .pvParameters    = NULL,
    .uxPriority      = tskIDLE_PRIORITY,
    .puxStackBuffer  = led2Stack,
    .xRegions = {
                    {ucSharedMemory1, SHARED_MEMORY_SIZE, portMPU_REGION_READ_WRITE | portMPU_REGION_EXECUTE_NEVER},
                    {ucSharedMemory2, SHARED_MEMORY_SIZE, portMPU_REGION_READ_WRITE | portMPU_REGION_EXECUTE_NEVER},
                    { 0,0,0},
                    { 0,0,0},
                }
};
//-------------------------------------------------------------------//

void SystemClock_16MHz_HSI(void)
{
    RCC_HSIEnable(1);
    while (!RCC_HSIRdy()) { /* wait */ }

    /* HSIDIV = /4  =>  hsi_ck = 16 MHz */
    RCC_HSIConfig(2);          /* 2 = divide by 4 */

    RCC_SetFlashLatency(0);

    RCC_SetD1CPRE(AHB_PRESCALER_DIV1);
    RCC_SetAHBPrescaler(AHB_PRESCALER_DIV1);
    RCC_SetD1PPRE(APB_PRESCALER_DIV1);
    RCC_SetD2PPRE1(APB_PRESCALER_DIV1);
    RCC_SetD2PPRE2(APB_PRESCALER_DIV1);
    RCC_SetD3PPRE(APB_PRESCALER_DIV1);

    RCC_SetSysClockSrc(RCC_SYSCLK_HSI);
}

void SystemClock_400MHz_HSI(void)
{
    /* 1) Enable HSI and wait */
    RCC_HSIEnable(1);
    while (!RCC_HSIRdy()) { /* wait */ }

    /* 2) HSIDIV = /8  =>  hsi_ck = 8 MHz (pll reference) */
    RCC_HSIConfig(3);                 /* 3 = /8 */

    /* 3) Flash latency: 4 wait states for 240 MHz AHB at VOS1 */
    RCC_SetFlashLatency(4);

    /* 4) Bus prescalers (do this BEFORE switching to PLL) */
    RCC_SetD1CPRE   (AHB_PRESCALER_DIV1);
    RCC_SetAHBPrescaler (AHB_PRESCALER_DIV2);
    RCC_SetD1PPRE   (APB_PRESCALER_DIV2);
    RCC_SetD2PPRE1  (APB_PRESCALER_DIV2);
    RCC_SetD2PPRE2  (APB_PRESCALER_DIV2);
    RCC_SetD3PPRE   (APB_PRESCALER_DIV2);

    /* 5) Configure PLL1 */
    RCC_PLL1_Init_t pll1 = {
        .pll_src    = RCC_PLLSRC_HSI,
        .divm       = 1,
        .divn       = 100,
        .divp       = 1,            /* encoding 1 -> output /2 -> 480 MHz */
        .divq       = 0,
        .divr       = 0,
        .pll_rge    = 3,            /* 8-16 MHz reference   */
        .pll_vcosel = 0,            /* wide VCO 192-836 MHz */
        .enable_p   = 1,
        .enable_q   = 0,
        .enable_r   = 0
    };
    RCC_PLL1Config(&pll1);
    RCC_PLL1Enable(1);
    while (!RCC_PLL1Ready()) { /* wait */ }

    /* 6) Switch SYSCLK to PLL1 */
    RCC_SetSysClockSrc(RCC_SYSCLK_PLL1);
}

/* ---------------------------------------------------------------------
 *  Shared pin setup helpers, used by all examples to avoid duplicating
 *  the configuration descriptors (which could otherwise drift apart).
 * ------------------------------------------------------------------- */
void LED_Init(void) {
    GPIO_PinConfig led;
    led.pin       = LED1_PIN;
    led.mode      = GPIO_MODE_OUTPUT;
    led.otype     = GPIO_OTYPE_PUSHPULL;
    led.speed     = GPIO_SPEED_LOW;
    led.pull      = GPIO_PULL_NONE;
    led.alternate = 0;
    GPIO_Init(LED1_PORT, &led);

    led.pin       = LED2_PIN;
    GPIO_Init(LED2_PORT, &led);
}

void HardDelay(uint32_t value)
{
	for(int i = 0; i < value; i++)
		for(int j = 0; j < 500; j++);
}

void vPortSetupTimerInterrupt(void) {
    // Intentionally left blank.
    // We are using TIM2, not the SysTick.
}

void rcc_Clk_Enable(void)
{
	RCC_PeriphEnable(RCC_APB4_SYSCFG);
	RCC_PeriphEnable(RCC_AHB4_GPIOB);
	RCC_PeriphEnable(RCC_AHB4_GPIOE);
	RCC_PeriphEnable(RCC_APB1L_TIM2);
}

bool power_config(void)
{
	volatile bool suppOk = false;
	//PWR_Init();
	PWR_SetVoltageScale(PWR_VOS_0);
	PWR_OverDriveEnable(1);
	PWR_BoostEnable(1);
	PWR_EnableBackupAccess();

	for(int i = 0; i< 100; i++)
	{
		if (PWR_RegulatorReady() != 0U) { suppOk = true; break;}
		if (PWR_GetVoltageScale() == PWR_VOS_0) { suppOk = true; break;}
		HardDelay(100);
	}
	return suppOk;
}

void timer_init(void)
{
	/* Initialize TIM2 for CC output of 1ms(1Khz) (16Mhz timer clock / (100 prescalar * 160 counter))*/
	H7_TIM_Init(TIM2, 100, 160, TIM_COUNTERMODE_UP);  // 80 MHz timer clock, 1 kHz frequency

	/* Configure channel 1 for PWM output, 50% duty cycle */
	H7_TIM_PWM_ConfigChannel(TIM2, 1, 500, TIM_OCPOLARITY_HIGH, TIM_OCMODE_PWM1);

	/* Enable CC1 interrupt */
	H7_TIM_EnableInterrupt(TIM2, TIM_CC2_INTERRUPT);

	/* Enable the timer */
	H7_TIM_Start(TIM2);

	NVIC_Init();
	NVIC_RegisterCallback(NVIC_IRQ_TIM2, TIM2_handler);
	NVIC_SetPriority(NVIC_IRQ_TIM2, 0x20U);
	NVIC_EnableIRQ(NVIC_IRQ_TIM2);
}

void Led1_Task(void *val)
{
	vTaskDelay( pdMS_TO_TICKS( 500 ) );
	for(;;)
	{
		ucSharedMemory1[0] = 0xA5;
		//*((uint32_t*)24000800) = 0xABCDEF12;
		GPIO_TogglePin(LED1_PORT, LED1_PIN);
		vTaskDelay( pdMS_TO_TICKS( 500 ) );
	}
}

void Led2_Task(void *val)
{
	vTaskDelay( pdMS_TO_TICKS( 500 ) );
	for(;;)
	{
		GPIO_TogglePin(LED2_PORT, LED2_PIN);
		vTaskDelay( pdMS_TO_TICKS( 500 ) );
		ucSharedMemory2[0] = 0x25;
		vTaskDelay( pdMS_TO_TICKS( 500 ) );
		ucSharedMemory2[1] = 0x25;
	}
}

/* Timer2 CC1 interrupt handler */
void TIM2_handler(void)
{
    if (TIM2->SR & TIM_SR_CC2IF)
    {

        TIM2->SR = ~TIM_SR_CC2IF;
        if (xTaskGetSchedulerState() != taskSCHEDULER_NOT_STARTED)
        {
        	xPortSysTickHandler();
        }
    }
}

//---------------------------------------------------------------------//

static void prvROAccessTask( void * pvParameters )
{
uint8_t ucVal;

	/* Unused parameters. */
	( void ) pvParameters;

	for( ; ; )
	{
		/* This task performs the following sequence for all the shared memory
		 * regions:
		 *
		 * 1. Perfrom a read access to the shared memory. Since this task has
		 *    RO access to the shared memory, the read operation is successful.
		 *
		 * 2. Set ucROTaskFaultTracker[ 0 ] to 1 before performing a write to
		 *    the shared memory. Since this task has Read Only access to the
		 *    shared memory, the write operation would result in a Memory Fault.
		 *    Setting ucROTaskFaultTracker[ 0 ] to 1 tells the Memory Fault
		 *    Handler that this is an expected fault. The handler recovers from
		 *    the expected fault gracefully by jumping to the next instruction.
		 *
		 * 3. Perfrom a write to the shared memory resulting in a memory fault.
		 *
		 * 4. Ensure that the write access did generate MemFault and the fault
		 *    handler did clear the  ucROTaskFaultTracker[ 0 ].
		 */
		/* Perform the above mentioned sequence on ucSharedMemory1. */
		ucVal = ucSharedMemory1[ 0 ];
		/* Silent compiler warnings about unused variables. */
		( void ) ucVal;
		ucROTaskFaultTracker[ 0 ] = 1;
		//ucSharedMemory1[ 0 ] = 0;
		configASSERT( ucROTaskFaultTracker[ 0 ] == 0 );

		/* Perform the above mentioned sequence on ucSharedMemory2. */
		ucVal = ucSharedMemory2[ 0 ];
		/* Silent compiler warnings about unused variables. */
		( void ) ucVal;
		ucROTaskFaultTracker[ 0 ] = 1;
		//ucSharedMemory2[ 0 ] = 0;
		configASSERT( ucROTaskFaultTracker[ 0 ] == 0 );

		/* Perform the above mentioned sequence on ucSharedMemory3. */
		ucVal = ucSharedMemory3[ 0 ];
		/* Silent compiler warnings about unused variables. */
		( void ) ucVal;
		ucROTaskFaultTracker[ 0 ] = 1;
		//ucSharedMemory3[ 0 ] = 0;
		configASSERT( ucROTaskFaultTracker[ 0 ] == 0 );

		/* Perform the above mentioned sequence on ucSharedMemory4. */
		ucVal = ucSharedMemory4[ 0 ];
		/* Silent compiler warnings about unused variables. */
		( void ) ucVal;
		ucROTaskFaultTracker[ 0 ] = 1;
		//ucSharedMemory4[ 0 ] = 0;
		configASSERT( ucROTaskFaultTracker[ 0 ] == 0 );

		/* Perform the above mentioned sequence on ucSharedMemory5. */
		ucVal = ucSharedMemory5[ 0 ];
		/* Silent compiler warnings about unused variables. */
		( void ) ucVal;
		ucROTaskFaultTracker[ 0 ] = 1;
		//ucSharedMemory5[ 0 ] = 0;
		configASSERT( ucROTaskFaultTracker[ 0 ] == 0 );

		/* Perform the above mentioned sequence on ucSharedMemory6. */
		ucVal = ucSharedMemory6[ 0 ];
		/* Silent compiler warnings about unused variables. */
		( void ) ucVal;
		ucROTaskFaultTracker[ 0 ] = 1;
		//ucSharedMemory6[ 0 ] = 0;
		configASSERT( ucROTaskFaultTracker[ 0 ] == 0 );

		/* Wait for a second. */
		vTaskDelay( pdMS_TO_TICKS( 1000 ) );
	}
}
/*-----------------------------------------------------------*/

static void prvRWAccessTask( void * pvParameters )
{
	/* Unused parameters. */
	( void ) pvParameters;

	for( ; ; )
	{
		/* This task has RW access to shared memories and therefore can write to
		 * them. */
		ucSharedMemory1[ 0 ] = 0;
		ucSharedMemory2[ 0 ] = 0;
		ucSharedMemory3[ 0 ] = 0;
		ucSharedMemory4[ 0 ] = 0;
		ucSharedMemory5[ 0 ] = 0;
		ucSharedMemory6[ 0 ] = 0;

		/* Wait for a second. */
		vTaskDelay( pdMS_TO_TICKS( 1000 ) );
	}
}
/*-----------------------------------------------------------*/

void vStartMPUDemo( void )
{
/**
 * Since stack of a task is protected using MPU, it must satisfy MPU
 * requirements as mentioned at the top of this file.
 */
static StackType_t xROAccessTaskStack[ configMINIMAL_STACK_SIZE ] __attribute__( ( aligned( configMINIMAL_STACK_SIZE * sizeof( StackType_t ) ) ) );
static StackType_t xRWAccessTaskStack[ configMINIMAL_STACK_SIZE ] __attribute__( ( aligned( configMINIMAL_STACK_SIZE * sizeof( StackType_t ) ) ) );
TaskParameters_t xROAccessTaskParameters =
{
	.pvTaskCode		= prvROAccessTask,
	.pcName			= "ROAccess",
	.usStackDepth	= configMINIMAL_STACK_SIZE,
	.pvParameters	= NULL,
	.uxPriority		= tskIDLE_PRIORITY,
	.puxStackBuffer	= xROAccessTaskStack,
	.xRegions		=	{
							{ ucSharedMemory1,					SHARED_MEMORY_SIZE,	portMPU_REGION_PRIVILEGED_READ_WRITE_UNPRIV_READ_ONLY | portMPU_REGION_EXECUTE_NEVER	},
							{ ucSharedMemory2,					SHARED_MEMORY_SIZE,	portMPU_REGION_PRIVILEGED_READ_WRITE_UNPRIV_READ_ONLY | portMPU_REGION_EXECUTE_NEVER	},
							{ ucSharedMemory3,					SHARED_MEMORY_SIZE,	portMPU_REGION_PRIVILEGED_READ_WRITE_UNPRIV_READ_ONLY | portMPU_REGION_EXECUTE_NEVER	},
							{ ucSharedMemory4,					SHARED_MEMORY_SIZE,	portMPU_REGION_PRIVILEGED_READ_WRITE_UNPRIV_READ_ONLY | portMPU_REGION_EXECUTE_NEVER	},
							{ ucSharedMemory5,					SHARED_MEMORY_SIZE,	portMPU_REGION_PRIVILEGED_READ_WRITE_UNPRIV_READ_ONLY | portMPU_REGION_EXECUTE_NEVER	},
							{ ucSharedMemory6,					SHARED_MEMORY_SIZE,	portMPU_REGION_PRIVILEGED_READ_WRITE_UNPRIV_READ_ONLY | portMPU_REGION_EXECUTE_NEVER	},
							{ ( void * ) ucROTaskFaultTracker,	SHARED_MEMORY_SIZE,	portMPU_REGION_READ_WRITE | portMPU_REGION_EXECUTE_NEVER								},
							{ 0,								0,					0																						},
							{ 0,								0,					0																						},
							{ 0,								0,					0																						},
							{ 0,								0,					0																						}
						}
};
TaskParameters_t xRWAccessTaskParameters =
{
	.pvTaskCode		= prvRWAccessTask,
	.pcName			= "RWAccess",
	.usStackDepth	= configMINIMAL_STACK_SIZE,
	.pvParameters	= NULL,
	.uxPriority		= tskIDLE_PRIORITY,
	.puxStackBuffer	= xRWAccessTaskStack,
	.xRegions		=	{
							{ ucSharedMemory1,	SHARED_MEMORY_SIZE,	portMPU_REGION_READ_WRITE | portMPU_REGION_EXECUTE_NEVER},
							{ ucSharedMemory2,	SHARED_MEMORY_SIZE,	portMPU_REGION_READ_WRITE | portMPU_REGION_EXECUTE_NEVER},
							{ ucSharedMemory3,	SHARED_MEMORY_SIZE,	portMPU_REGION_READ_WRITE | portMPU_REGION_EXECUTE_NEVER},
							{ ucSharedMemory4,	SHARED_MEMORY_SIZE,	portMPU_REGION_READ_WRITE | portMPU_REGION_EXECUTE_NEVER},
							{ ucSharedMemory5,	SHARED_MEMORY_SIZE,	portMPU_REGION_READ_WRITE | portMPU_REGION_EXECUTE_NEVER},
							{ ucSharedMemory6,	SHARED_MEMORY_SIZE,	portMPU_REGION_READ_WRITE | portMPU_REGION_EXECUTE_NEVER},
							{ 0,				0,					0														},
							{ 0,				0,					0														},
							{ 0,				0,					0														},
							{ 0,				0,					0														},
							{ 0,				0,					0														}
						}
};

	/* Create an unprivileged task with RO access to ucSharedMemory. */
	xTaskCreateRestricted( &( xROAccessTaskParameters ), NULL );

	/* Create an unprivileged task with RW access to ucSharedMemory. */
	xTaskCreateRestricted( &( xRWAccessTaskParameters ), NULL );
}
//-----------------------------------------------------------------------------//

int main(void) {

	//SCB->CPACR |= ((3UL << (10 * 2)) | (3UL << (11 * 2)));

	//SystemClock_400MHz_HSI();
    SystemClock_16MHz_HSI();

	rcc_Clk_Enable();
	bool init = power_config();
	if(init == false)
	{
		// error handling
		return 0;
	}

    LED_Init();


    xTaskCreateRestricted(&( Led1_TaskPara ), NULL);
    xTaskCreateRestricted(&( Led2_TaskPara ), NULL);
    //vStartMPUDemo();

    timer_init();
    vTaskStartScheduler();


    while (1) {
    	//GPIO_TogglePin(LED1_PORT, LED1_PIN);
    	//GPIO_TogglePin(LED2_PORT, LED2_PIN);
    	//HardDelay(500);
    }

    return 0;
}
#endif

void vApplicationIdleHook(void) {
    // This runs whenever no other task is ready to run
    // Enter Sleep Mode
    //__WFI();
    		//GPIO_TogglePin(GPIOC, GPIO_PIN_8);
            //Delay_ms(10);
	//IdleCounter++;
}

void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName) {
    // Trigger a breakpoint or reset the system here
    while (1) {
		//GPIO_TogglePin(GPIOC, GPIO_PIN_9);
			for(int i = 0; i < 20000; i++);
	}
}

void vApplicationMallocFailedHook(void)
{
    while(1)
    {
        /* Memory exhausted */
    	for(int i = 0; i < 20000; i++);
    }
}

/* Required for static allocation of the Idle Task */
void vApplicationGetIdleTaskMemory(StaticTask_t **ppxIdleTaskTCBBuffer,
                                   StackType_t **ppxIdleTaskStackBuffer,
                                   uint32_t *pulIdleTaskStackSize) {
    static StaticTask_t xIdleTaskTCB;
    static StackType_t xIdleTaskStack[configMINIMAL_STACK_SIZE];

    *ppxIdleTaskTCBBuffer = &xIdleTaskTCB;
    *ppxIdleTaskStackBuffer = xIdleTaskStack;
    *pulIdleTaskStackSize = configMINIMAL_STACK_SIZE;
}

/* Required for static allocation of the Timer Task */
void vApplicationGetTimerTaskMemory(StaticTask_t **ppxTimerTaskTCBBuffer,
                                    StackType_t **ppxTimerTaskStackBuffer,
                                    uint32_t *pulTimerTaskStackSize) {
    static StaticTask_t xTimerTaskTCB;
    static StackType_t xTimerTaskStack[configTIMER_TASK_STACK_DEPTH];

    *ppxTimerTaskTCBBuffer = &xTimerTaskTCB;
    *ppxTimerTaskStackBuffer = xTimerTaskStack;
    *pulTimerTaskStackSize = configTIMER_TASK_STACK_DEPTH;
}

void MemManage_Handler(void)

{
    // Read MMAR (MemManage Fault Address Register) to see the bad address
    //uint32_t faultAddr = SCB->MMFAR;
    // Force a break or system reset
    while(1);
}
