/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "FreeRTOS.h"
#include "rcc.h"
#include "gpio.h"
#include "STM32F0Time.h"
#include "FlashF051.h"
#include "uartF051.h"
#include "task.h"
#include "queue.h"



volatile uint32_t timerTickCount = 0;

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void LedTask(void *pvParameters);

void Delay_ms(uint32_t ms) {
    uint32_t i, j;
    for (i = 0; i < ms; i++) {
        for (j = 0; j < 8000; j++) {
            //NOP();
        }
    }
}

static void Timer2_Callback(void) {
    //timerTickCount++;
    if (xTaskGetSchedulerState() != taskSCHEDULER_NOT_STARTED) {
      /* Call tick handler */
    	xPortSysTickHandler();
    }
}

void timer_init(void)
{
	uint32_t t2clk = STM32F0Timer_GetTimerClockHz(TIMER2);
	if (!STM32F0Timer_ConfigurePeriodUs(TIMER2, t2clk, 1000U)) {
	        while (1);
	    }
	STM32F0Timer_SetUpdateCallback(TIMER2, Timer2_Callback);
	STM32F0Timer_EnableUpdateInterrupt(TIMER2, true);
	STM32F0Timer_Start(TIMER2);
}

void led_gpio_init(void) {
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    /* Enable GPIOC clock for LED on PC8 */
    GPIO_EnableClock(GPIOC);

    /* Configure PC8 as output */
    GPIO_InitStruct.Pin = GPIO_PIN_8;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT;
    GPIO_InitStruct.Ot = GPIO_OTYPE_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_LOW;
    GPIO_InitStruct.Pull = GPIO_PULL_NO;
    GPIO_Init(GPIOC, &GPIO_InitStruct);

    /* Configure PC8 as output */
    GPIO_InitStruct.Pin = GPIO_PIN_9;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT;
    GPIO_InitStruct.Ot = GPIO_OTYPE_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_LOW;
    GPIO_InitStruct.Pull = GPIO_PULL_NO;
    GPIO_Init(GPIOC, &GPIO_InitStruct);
}

void SystemClock_Config_48MHz(void) {
    RCC_Config config = {
        .system_clock_source = CLOCK_SOURCE_PLL,
        .target_frequency = SYSTEM_CLOCK_48MHZ,
        .hse_enabled = true,
        .pll_enabled = true,
        .pll_source = PLL_SOURCE_HSE,
        .pll_multiplier = 6,  // HSE 8MHz * 6 = 48MHz
        .ahb_prescaler = AHB_PRESCALER_1,
        .apb_prescaler = APB_PRESCALER_1,
        .hsi48_enabled = false,
        .css_enabled = true
    };

    RCC_Init(&config);

    if(FLASH_ConfigureForFrequency(48000000) != FLASH_STATUS_OK)
    {
    	while(1);
    }
}

void vPortSetupTimerInterrupt(void) {
    // Intentionally left blank.
    // We are using TIM6, not the SysTick.
}

int main(void)
{
	SystemClock_Config_48MHz();
	led_gpio_init();

    timer_init();
    STM32F0Timer_Stop(TIMER2);

    xTaskCreate(
        LedTask,
        "LED",
        128,
        NULL,
        tskIDLE_PRIORITY + 2,
        NULL
    );

    UART_App_Init();

    STM32F0Timer_Start(TIMER2);

    vTaskStartScheduler();

    /* Main loop - toggle LED */
    while (1) {
    		//GPIO_TogglePin(GPIOC, GPIO_PIN_8);
            Delay_ms(1000);
    }
}

void LedTask(void *pvParameters)
{
    TickType_t xLastWakeTime;

    while(xTaskGetSchedulerState() == taskSCHEDULER_NOT_STARTED) {
      /* Call tick handler */
    }

    /* Initialize xLastWakeTime with the current tick count */
    xLastWakeTime = xTaskGetTickCount();

    while (1)
    {
        /* Toggle PA5 */
    	GPIO_TogglePin(GPIOC, GPIO_PIN_9);

        /* Wait until 100 ms from the previous wake time */
//        vTaskDelayUntil(
//            &xLastWakeTime,
//            pdMS_TO_TICKS(100)
//        );

    	vTaskDelay(100);
    }
}

void vApplicationIdleHook(void) {
    // This runs whenever no other task is ready to run
    // Enter Sleep Mode
    //__WFI(); 
    		GPIO_TogglePin(GPIOC, GPIO_PIN_8);
            //Delay_ms(10);
}

void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName) {
    // Trigger a breakpoint or reset the system here
    while (1) {
		//GPIO_TogglePin(GPIOC, GPIO_PIN_9);
        Delay_ms(1000);
}
}
