/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "rcc.h"
#include "gpio.h"
#include "STM32F0Time.h"
#include "FlashF051.h"
#include "uartF051.h"
#include "main.h"

TaskHandle_t ledTaskHandle;
TaskHandle_t monitoringTaskHandle;
TaskHandle_t uartTaskHandle;

TimerHandle_t tmr_1sec;

volatile uint32_t timerTickCount = 0;
volatile bool systemInitialized = true;
volatile uint32_t ulHighFrequencyTimerTicks = 0;

volatile uint32_t IdleCounter = 0;
volatile uint8_t CPU_Usage = 0;

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void LedTask(void *pvParameters);
void Monitoring_Task(void *parameter);
void ConfigureTimerForRunTimeStats(void);

void Delay_ms(uint32_t ms) {
    uint32_t i, j;
    for (i = 0; i < ms; i++) {
        for (j = 0; j < 8000; j++) {
            //NOP();
        }
    }
}

static void Timer2_Callback(void) {
    //timerTickCount++;
    if (xTaskGetSchedulerState() != taskSCHEDULER_NOT_STARTED) {
      /* Call tick handler */
    	xPortSysTickHandler();
    }
}

static void TIMER16_Callback(void) {
    ulHighFrequencyTimerTicks++;

}

void timer_init(void)
{
	uint32_t t2clk = STM32F0Timer_GetTimerClockHz(TIMER2);
	if (!STM32F0Timer_ConfigurePeriodUs(TIMER2, t2clk, 1000U)) {
	        while (1);
	    }
	STM32F0Timer_SetUpdateCallback(TIMER2, Timer2_Callback);
	STM32F0Timer_EnableUpdateInterrupt(TIMER2, true);
	STM32F0Timer_Start(TIMER2);

    //---- This timer is for debugging of FreeRTOS for Task States ------//
    ConfigureTimerForRunTimeStats();
}

void led_gpio_init(void) {
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    /* Enable GPIOC clock for LED on PC8 */
    GPIO_EnableClock(GPIOC);

    /* Configure PC8 as output */
    GPIO_InitStruct.Pin = GPIO_PIN_8;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT;
    GPIO_InitStruct.Ot = GPIO_OTYPE_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_LOW;
    GPIO_InitStruct.Pull = GPIO_PULL_NO;
    GPIO_Init(GPIOC, &GPIO_InitStruct);

    /* Configure PC8 as output */
    GPIO_InitStruct.Pin = GPIO_PIN_9;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT;
    GPIO_InitStruct.Ot = GPIO_OTYPE_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_LOW;
    GPIO_InitStruct.Pull = GPIO_PULL_NO;
    GPIO_Init(GPIOC, &GPIO_InitStruct);
}

void SystemClock_Config_48MHz(void) {
    RCC_Config config = {
        .system_clock_source = CLOCK_SOURCE_PLL,
        .target_frequency = SYSTEM_CLOCK_48MHZ,
        .hse_enabled = true,
        .pll_enabled = true,
        .pll_source = PLL_SOURCE_HSE,
        .pll_multiplier = 6,  // HSE 8MHz * 6 = 48MHz
        .ahb_prescaler = AHB_PRESCALER_1,
        .apb_prescaler = APB_PRESCALER_1,
        .hsi48_enabled = false,
        .css_enabled = true
    };

    RCC_Init(&config);

    if(FLASH_ConfigureForFrequency(48000000) != FLASH_STATUS_OK)
    {
    	while(1);
    }
}

void vPortSetupTimerInterrupt(void) {
    // Intentionally left blank.
    // We are using TIM6, not the SysTick.
}
#define MAX_IDLE_COUNT 614491u
void tmr1secCallBack(TimerHandle_t xTimer)
{
	if(xTimer == tmr_1sec)
	{
		if(IdleCounter < MAX_IDLE_COUNT)
		{
			CPU_Usage = 100 - ((IdleCounter * 100) / MAX_IDLE_COUNT);
		}
		IdleCounter = 0;
	}
}

int main(void)
{
	SystemClock_Config_48MHz();
	led_gpio_init();

    timer_init();
    STM32F0Timer_Stop(TIMER2);

    xTaskCreate(
        LedTask,
        "LED",
        128,
        NULL,
        tskIDLE_PRIORITY + 2,
        &ledTaskHandle
    );


    xTaskCreate(
    	Monitoring_Task,
        "Monitor_Task",
        128,
        NULL,
        tskIDLE_PRIORITY + 2,
        &monitoringTaskHandle
    );

    UART_App_Init();

    tmr_1sec = xTimerCreate("1Sec_Timer",
    						pdMS_TO_TICKS(1000),
							pdTRUE,
							NULL,
							tmr1secCallBack);

    xTimerStart(tmr_1sec, 0);
    STM32F0Timer_Start(TIMER2);

    vTaskStartScheduler();

    /* Main loop - toggle LED */
    while (1) {
    		//GPIO_TogglePin(GPIOC, GPIO_PIN_8);
            Delay_ms(pdMS_TO_TICKS(100));
    }
}


static inline char* TaskStateDecode(uint8_t state)
{
	if(state==0)
		return "eRunning";
	else if(state==1)
		return "eReady";
	else if(state==2)
		return "eBlocked";
	else if(state==3)
		return "eSuspended";
	else if(state==4)
		return "eDeleted";
	else if(state==5)
		return "eInvalid";
	else
		return "undefined";
}

volatile uint8_t prtStr[200] = {0};
void Monitoring_Task(void *parameter)
{

	TaskStatus_t TaskStatusArray[10];
	uint32_t TotalRunTime;

    while(xTaskGetSchedulerState() == taskSCHEDULER_NOT_STARTED) {
    }
    systemInitialized = true;

	while(1)
	{
		memset((char *)prtStr, 0x00, sizeof(prtStr));
		sprintf((char *)prtStr, "Idle Usage(Pers)= %d\r\n", (unsigned int)CPU_Usage);
		UART_SendStringIT(USART1, (const char *)prtStr);
#if 0
		UBaseType_t TaskCount = uxTaskGetSystemState(TaskStatusArray,
																  10,
													   &TotalRunTime);
		UART_SendStringIT(USART1, (const char *)"\r\n---------------------Task State---------------------");
		memset((char *)prtStr, 0x00, sizeof(prtStr));
		for(uint8_t i = 0; i < TaskCount; i++)
		{
			sprintf((char *)prtStr, "\r\n\
							 Task Name:- %s\n\
							 State:- %s\n\
							 Stack High Mark:- %d\n\
							 CPU Usage(%) = %d\n", TaskStatusArray[i].pcTaskName,
							 TaskStateDecode(TaskStatusArray[i].eCurrentState),
							 (unsigned int)TaskStatusArray[i].usStackHighWaterMark,
							 CPU_Usage);//(unsigned int)(TaskStatusArray[i].ulRunTimeCounter * 100)/TotalRunTime);
			UART_SendStringIT(USART1, (const char *)prtStr);
			vTaskDelay(pdMS_TO_TICKS(500));
		}
#endif
		vTaskDelay(pdMS_TO_TICKS(500));
        GPIO_TogglePin(GPIOC, GPIO_PIN_8);
	}
}
#if 1
void LedTask(void *pvParameters)
{
    TickType_t xLastWakeTime;

    while(systemInitialized == false);

    /* Initialize xLastWakeTime with the current tick count */
    xLastWakeTime = xTaskGetTickCount();

    while (1)
    {
        /* Toggle PA5 */
    	GPIO_TogglePin(GPIOC, GPIO_PIN_9);

        /* Wait until 100 ms from the previous wake time */
//        vTaskDelayUntil(
//            &xLastWakeTime,
//            pdMS_TO_TICKS(pdMS_TO_TICKS(500))
//        );
		for(int i = 0; i<500000; i++)
			for(int j = 0; j<5000; j++);
    	vTaskDelay(pdMS_TO_TICKS(500));
    }
}
#endif
void vApplicationIdleHook(void) {
    // This runs whenever no other task is ready to run
    // Enter Sleep Mode
    //__WFI(); 
    		//GPIO_TogglePin(GPIOC, GPIO_PIN_8);
            //Delay_ms(10);
	IdleCounter++;
}

void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName) {
    // Trigger a breakpoint or reset the system here
    while (1) {
		//GPIO_TogglePin(GPIOC, GPIO_PIN_9);
			Delay_ms(1000);
	}
}

void vApplicationMallocFailedHook(void)
{
    while(1)
    {
        /* Memory exhausted */
    	Delay_ms(1000);
    }
}

void ConfigureTimerForRunTimeStats(void)
{
   	uint32_t t2clk = STM32F0Timer_GetTimerClockHz(TIMER16);
	if (!STM32F0Timer_ConfigurePeriodUs(TIMER16, t2clk, 10U)) {
	        while (1);
	    }
	STM32F0Timer_SetUpdateCallback(TIMER16, TIMER16_Callback);
	STM32F0Timer_EnableUpdateInterrupt(TIMER16, true);
	STM32F0Timer_Start(TIMER16);
}
