/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "rcc.h"
#include "gpio.h"
#include "STM32F0Time.h"
#include "FlashF051.h"
#include "uartF051.h"
#include "main.h"

#define LED1_STACK_SIZE             128
#define LED2_STACK_SIZE             128
#define STATIC_QUEUE_LEN            200
#define STATIC_QUEUE_ITEM_SIZE      sizeof(uint8_t)

static StackType_t led1TaskStack[LED1_STACK_SIZE];
static StackType_t led2TaskStack[LED2_STACK_SIZE];

static StaticTask_t led1TaskHansl;
static StaticTask_t led2TaskHansl; 

static StaticQueue_t xStaticQueueBuffer;
static uint8_t xQueueBuffer[STATIC_QUEUE_LEN*STATIC_QUEUE_ITEM_SIZE];
QueueHandle_t xtransferQueue = NULL;

static StaticTask_t uartTaskHansl;

TaskHandle_t uartTaskHandle;

TimerHandle_t tmr_1sec;

volatile bool systemInitialized = true;
volatile uint32_t ulHighFrequencyTimerTicks = 0;

volatile uint32_t IdleCounter = 0;
volatile uint8_t CPU_Usage = 0;

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void LedTask(void *pvParameters);
void Led2Task(void *pvParameters);

void Delay_ms(uint32_t ms) {
    uint32_t i, j;
    for (i = 0; i < ms; i++) {
        for (j = 0; j < 8000; j++) {
            //NOP();
        }
    }
}

static void Timer2_Callback(void) {
    if (xTaskGetSchedulerState() != taskSCHEDULER_NOT_STARTED) {
      /* Call tick handler */
    	xPortSysTickHandler();
    }
}

static void TIMER16_Callback(void) {
    ulHighFrequencyTimerTicks++;

}

void timer_init(void)
{
	uint32_t t2clk = STM32F0Timer_GetTimerClockHz(TIMER2);
	if (!STM32F0Timer_ConfigurePeriodUs(TIMER2, t2clk, 1000U)) {
	        while (1);
	    }
	STM32F0Timer_SetUpdateCallback(TIMER2, Timer2_Callback);
	STM32F0Timer_EnableUpdateInterrupt(TIMER2, true);
	STM32F0Timer_Start(TIMER2);

}

void led_gpio_init(void) {
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    /* Enable GPIOC clock for LED on PC8 */
    GPIO_EnableClock(GPIOC);

    /* Configure PC8 as output */
    GPIO_InitStruct.Pin = GPIO_PIN_8;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT;
    GPIO_InitStruct.Ot = GPIO_OTYPE_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_LOW;
    GPIO_InitStruct.Pull = GPIO_PULL_NO;
    GPIO_Init(GPIOC, &GPIO_InitStruct);

    /* Configure PC8 as output */
    GPIO_InitStruct.Pin = GPIO_PIN_9;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT;
    GPIO_InitStruct.Ot = GPIO_OTYPE_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_LOW;
    GPIO_InitStruct.Pull = GPIO_PULL_NO;
    GPIO_Init(GPIOC, &GPIO_InitStruct);
}

void SystemClock_Config_48MHz(void) {
    RCC_Config config = {
        .system_clock_source = CLOCK_SOURCE_PLL,
        .target_frequency = SYSTEM_CLOCK_48MHZ,
        .hse_enabled = true,
        .pll_enabled = true,
        .pll_source = PLL_SOURCE_HSE,
        .pll_multiplier = 6,  // HSE 8MHz * 6 = 48MHz
        .ahb_prescaler = AHB_PRESCALER_1,
        .apb_prescaler = APB_PRESCALER_1,
        .hsi48_enabled = false,
        .css_enabled = true
    };

    RCC_Init(&config);

    if(FLASH_ConfigureForFrequency(48000000) != FLASH_STATUS_OK)
    {
    	while(1);
    }
}

void vPortSetupTimerInterrupt(void) {
    // Intentionally left blank.
    // We are using TIM6, not the SysTick.
}
#define MAX_IDLE_COUNT 614491u
void tmr1secCallBack(TimerHandle_t xTimer)
{
	if(xTimer == tmr_1sec)
	{
		if(IdleCounter < MAX_IDLE_COUNT)
		{
			CPU_Usage = 100 - ((IdleCounter * 100) / MAX_IDLE_COUNT);
		}
		IdleCounter = 0;
	}
}

int main(void)
{
	SystemClock_Config_48MHz();
	led_gpio_init();

    timer_init();
    STM32F0Timer_Stop(TIMER2);

    xTaskCreateStatic(
        LedTask,
        "LED",
        LED1_STACK_SIZE,
        NULL,
        tskIDLE_PRIORITY + 2,
        led1TaskStack,
        &led1TaskHansl
    );


    xTaskCreateStatic(
    	Led2Task,
        "Monitor_Task",
        LED2_STACK_SIZE,
        NULL,
        tskIDLE_PRIORITY + 2,
        led2TaskStack,
        &led2TaskHansl
    );

    //UART_App_Init();

    STM32F0Timer_Start(TIMER2);

    vTaskStartScheduler();

    /* Main loop - toggle LED */
    while (1) {
        Delay_ms(pdMS_TO_TICKS(100));
    }
}


void LedTask(void *pvParameters)
{
    TickType_t xLastWakeTime;
    uint8_t dataRecv[STATIC_QUEUE_LEN] = {0x4B};
    uint16_t x = 0;

    while(systemInitialized == false);

    /* Initialize xLastWakeTime with the current tick count */
    xLastWakeTime = xTaskGetTickCount();


    while (1)
    {
    	vTaskDelay(pdMS_TO_TICKS(1000));
        /* Toggle PA5 */
    	GPIO_TogglePin(GPIOC, GPIO_PIN_8);
        BaseType_t recvVal = xQueueReceive(xtransferQueue, &dataRecv[x++], portMAX_DELAY);
        if(recvVal != pdTRUE)
        {
        	x--;
            // Process received data
        }
    }
}

void Led2Task(void *pvParameters)
{
    TickType_t xLastWakeTime;
    uint8_t data[STATIC_QUEUE_LEN] = {0x4B};
    uint16_t x = 0;

    while(systemInitialized == false);

    /* Initialize xLastWakeTime with the current tick count */
    xLastWakeTime = xTaskGetTickCount();
    xtransferQueue = xQueueCreateStatic(STATIC_QUEUE_LEN,
                                   STATIC_QUEUE_ITEM_SIZE,
                                   xQueueBuffer,
                                   &xStaticQueueBuffer);
    memset((char *)data, 0x4B, sizeof(data));
    while (1)
    {
        /* Toggle PA5 */
    	GPIO_TogglePin(GPIOC, GPIO_PIN_9);

    	xQueueSend(xtransferQueue, &data[x++], 100);
    	vTaskDelay(pdMS_TO_TICKS(100));
    }
}

#if (configUSE_IDLE_HOOK == 1)
void vApplicationIdleHook(void) {
    // This runs whenever no other task is ready to run
    // Enter Sleep Mode
    //__WFI(); 
    		//GPIO_TogglePin(GPIOC, GPIO_PIN_8);
            //Delay_ms(10);
	IdleCounter++;
}
#endif

#if (configSUPPORT_STATIC_ALLOCATION == 1)
void vApplicationGetIdleTaskMemory(StaticTask_t **ppxIdleTaskTCBBuffer,
                                   StackType_t **ppxIdleTaskStackBuffer,
                                   uint32_t *pulIdleTaskStackSize) {
    static StaticTask_t xIdleTaskTCB;
    static StackType_t xIdleTaskStack[configMINIMAL_STACK_SIZE];

    *ppxIdleTaskTCBBuffer = &xIdleTaskTCB;
    *ppxIdleTaskStackBuffer = xIdleTaskStack;
    *pulIdleTaskStackSize = configMINIMAL_STACK_SIZE;
}
#endif

void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName) {
    // Trigger a breakpoint or reset the system here
    while (1) {
		//GPIO_TogglePin(GPIOC, GPIO_PIN_9);
			Delay_ms(1000);
	}
}

void vApplicationMallocFailedHook(void)
{
    while(1)
    {
        /* Memory exhausted */
    	Delay_ms(1000);
    }
}
